---
# Elasticsearch Settings
elasticsearch_host: localhost
elasticsearch_index: ipdatabase

# ipset providers to ignore
ignore_providers: []

# ipset categories to ignore
ignore_categories:
  - unroutable      # This will include private address space, and we will match against internal data which includes pridate address space
  - geolocation     # Geolocation data
  - organizations   # Includes mostly known good hosts

# ipset databases to ignore
ignore_databases:
  - firehol_webserver  # Only relevant to web traffic
  - hphosts_emd        # Too many false positives
  - jigsaw_attacks     # Out of date, need to subscribe to get recent database

# overwrite reputation score for specific databases
reputation_scores:
  firehol_level4: -1

# Whitelist specific IP addresses (+100 reputation score)
whitelist:
  - 8.8.8.8
